'use strict';
const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
const KEY = 'huanxing.v1';
const moods = [
  {id:'calm',name:'平静',face:'◡',color:'#dce6d2',score:4},
  {id:'happy',name:'开心',face:'⌣',color:'#f4e6b6',score:5},
  {id:'tired',name:'疲惫',face:'–',color:'#e5ded3',score:3},
  {id:'anxious',name:'焦虑',face:'﹏',color:'#eddbc6',score:2},
  {id:'low',name:'低落',face:'⌢',color:'#dce3ee',score:1},
  {id:'unsure',name:'说不清',face:'· ·',color:'#e8e3ec',score:null}
];
const triggers = ['学业 / DDL','工作','人际关系','亲密关系','经济压力','睡眠','说不清'];
const practices = [
  {id:'breath',name:'把自己带回此刻',type:'呼吸觉察',minutes:2,symbol:'◎',description:'放松肩膀，留意空气轻轻进出。只跟随你舒服的节奏。',steps:['舒适地坐着，双脚轻放地面。','自然吸气，感受身体轻微的起伏。','缓缓呼气，不需要屏息，也不用刻意深呼吸。','走神时，温柔地把注意力带回来。']},
  {id:'ground',name:'落在当下的小练习',type:'感官觉察',minutes:2,symbol:'✧',description:'从身边的颜色、声音和触感开始，重新感受此刻。',steps:['找到身边 3 样看得见的东西，留意它们的颜色。','听一听，辨认 2 种此刻的声音。','感受脚底或手掌接触到的表面。','看看四周，告诉自己：我正在这里。']},
  {id:'music',name:'让声音陪你一会儿',type:'环境音',minutes:5,symbol:'♫',description:'一段轻柔的合成音景。戴不戴耳机都可以，音量由你决定。',steps:['先把音量调低，找到舒适的位置。','让声音留在背景，不必努力集中注意。','如果声音让你不舒服，可以随时停止。']},
  {id:'stretch',name:'松开紧绷的肩膀',type:'轻运动',minutes:2,symbol:'↟',description:'离开紧绷的姿势，给肩颈一点温和的活动空间。',steps:['坐稳或站稳，双肩自然下垂。','在舒适范围内，轻轻抬肩，然后放松。','慢慢转动肩膀，再舒展双手。','任何动作引起疼痛，就停止；不追求幅度。']},
  {id:'meditate',name:'允许念头路过',type:'短时冥想',minutes:5,symbol:'◌',description:'不需要清空大脑，试着让念头来来去去。',steps:['找到舒适姿势，可以睁眼，也可以轻闭双眼。','将注意力放在身体与椅子或地面的接触处。','念头出现时，轻轻觉察：“我在想一件事。”','不急着解决它，把注意力带回身体。']},
  {id:'walk',name:'走一小段，没有目的',type:'轻运动',minutes:5,symbol:'⌁',description:'如果环境允许，站起来走走，看看窗外或走廊里的光。',steps:['选择安全、熟悉的路线，留意周围环境。','收起屏幕，用舒适的步速走一小段。','留意脚步、光线和空气。','回到原处，感受一下身体现在的状态。']}
];
let storageError = false;
function load(){try{const raw=localStorage.getItem(KEY);if(!raw)return {entries:[],feedback:[]};const v=JSON.parse(raw);if(!Array.isArray(v.entries)||!Array.isArray(v.feedback))throw Error();if(v.entries.some(e=>!e||typeof e.id!=='string'||!Array.isArray(e.moods)||!e.moods.every(m=>moods.some(x=>x.id===m))||typeof e.note!=='string'||!Array.isArray(e.triggers)||!e.triggers.every(t=>triggers.includes(t))||!Number.isFinite(e.intensity)||!Number.isFinite(Date.parse(e.date))))throw Error();return v;}catch{storageError=true;return {entries:[],feedback:[]};}}
let state=load();
const selectedMoods=new Set(),selectedTriggers=new Set();
function persist(next){try{localStorage.setItem(KEY,JSON.stringify(next));state=next;return true;}catch{toast('无法保存：请检查浏览器存储权限或剩余空间。');return false;}}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toast.timeout);toast.timeout=setTimeout(()=>$('#toast').classList.remove('visible'),3500);}
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dateText=d=>new Date(d).toLocaleString('zh-CN',{month:'long',day:'numeric',hour:'2-digit',minute:'2-digit'});
const moodNames=e=>e.moods.map(id=>moods.find(m=>m.id===id)?.name||'').join(' · ');
const empty=(title,desc)=>`<div class="empty-state"><span>✧</span><h2>${title}</h2><p>${desc}</p><a href="#today" class="outline">记录此刻 ↗</a></div>`;
function setup(){
 $('#date-label').textContent=new Date().toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'});
 $('#mood-options').innerHTML=moods.map(m=>`<button type="button" class="mood-button" data-mood="${m.id}" aria-pressed="false"><span class="mood-face" aria-hidden="true" style="background:${m.color}">${m.face}</span>${m.name}</button>`).join('');
 $('#trigger-options').innerHTML=triggers.map(t=>`<button type="button" class="tag" aria-pressed="false">${t}</button>`).join('');
 $('#journal-filter').insertAdjacentHTML('beforeend',moods.map(m=>`<option value="${m.id}">${m.name}</option>`).join(''));
 $$('.mood-button').forEach(b=>b.addEventListener('click',()=>toggle(b,selectedMoods,b.dataset.mood)));
 $$('.tag').forEach(b=>b.addEventListener('click',()=>toggle(b,selectedTriggers,b.textContent)));
 $('#intensity').addEventListener('input',()=>$('#intensity-value').textContent=`${$('#intensity').value} / 5`);
 $('#entry-form').addEventListener('submit',e=>{e.preventDefault();if(!selectedMoods.size){toast('先选一种心情吧，“说不清”也可以。');$('.mood-button').focus();return;}const entry={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),date:new Date().toISOString(),moods:[...selectedMoods],intensity:Number($('#intensity').value),note:$('#note').value.trim(),triggers:[...selectedTriggers]};if(!persist({...state,entries:[entry,...state.entries]}))return;$('#entry-form').reset();$('#intensity-value').textContent='3 / 5';selectedMoods.clear();selectedTriggers.clear();$$('[aria-pressed=true]').forEach(b=>b.setAttribute('aria-pressed','false'));render();toast('这一刻，已经好好收下了。');});
 $('#journal-filter').addEventListener('change',renderJournal);$('#duration-filter').addEventListener('change',renderCare);
 window.addEventListener('hashchange',route);window.addEventListener('storage',e=>{if(e.key===KEY){state=load();render();}});
 document.addEventListener('click',e=>{const b=e.target.closest('[data-practice]');if(b)openPractice(b.dataset.practice);const del=e.target.closest('[data-delete]');if(del)confirmDeletion(()=>{if(persist({...state,entries:state.entries.filter(x=>x.id!==del.dataset.delete)})){render();toast('这条记录已删除。');}});});
 $$('.close-dialog').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));$('#support').addEventListener('click',()=>$('#support-dialog').showModal());$('.close-support').addEventListener('click',()=>$('#support-dialog').close());
 $('#practice-dialog').addEventListener('close',stopPractice);$('#cancel-delete').addEventListener('click',()=>$('#confirm-dialog').close());
 $('#clear-data').addEventListener('click',()=>confirmDeletion(()=>{if(persist({entries:[],feedback:[]})){render();toast('本地日记和练习反馈已删除。');}}));
 $('#export').addEventListener('click',()=>{const blob=new Blob([JSON.stringify({app:'缓星',version:1,exportedAt:new Date().toISOString(),...state},null,2)],{type:'application/json'});const u=URL.createObjectURL(blob);const a=document.createElement('a');a.href=u;a.download=`缓星日记-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);toast('已导出，请妥善保存日记文件。');});
 render();route();if(storageError)toast('本地数据无法读取；请先检查或备份浏览器数据。');
}
function toggle(b,set,value){set.has(value)?set.delete(value):set.add(value);b.setAttribute('aria-pressed',String(set.has(value)));}
function route(){const names={today:'此刻',journal:'情绪日记',insights:'看见自己',care:'自我关怀',settings:'我的空间'};const key=location.hash.slice(1) in names?location.hash.slice(1):'today';$$('.view').forEach(v=>v.hidden=v.id!==`view-${key}`);$$('nav a').forEach(a=>{a.classList.toggle('active',a.dataset.view===key);if(a.dataset.view===key)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});$('#breadcrumb').textContent=`我的空间 / ${names[key]}`;document.title=`${names[key]} · 缓星`;window.scrollTo(0,0);}
function render(){renderWeek();renderJournal();renderInsights();renderCare();const e=state.entries[0];$('#latest-entry').innerHTML=e?`<p>${escapeHTML(moodNames(e))}</p><p>${escapeHTML(e.note.slice(0,75)||'今天的感受，值得被记住。')}</p><time>${dateText(e.date)}</time>`:'<p class="muted">第一颗星，还在等你。<br>从今天的一个感受开始吧。</p>';}
function renderWeek(){const days=Array.from({length:7},(_,i)=>{const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-6+i);const list=state.entries.filter(e=>new Date(e.date).toDateString()===d.toDateString());const scores=list.flatMap(e=>e.moods.map(id=>moods.find(m=>m.id===id).score).filter(x=>x!==null));return {d,count:list.length,value:scores.length?scores.reduce((a,b)=>a+b,0)/scores.length:null};});$('#week-chart').innerHTML=`<div class="week-bars">${days.map(({d,count,value},i)=>`<div class="day-bar" title="${d.getMonth()+1}/${d.getDate()}：${count} 条记录${value===null?'，暂无可绘制心情':''}"><div class="bar-track"><div class="bar ${value===null?'empty':''}" style="height:${value===null?4:value*13}px"></div></div>${i===6?'今天':`${d.getMonth()+1}/${d.getDate()}`}</div>`).join('')}</div><span class="small muted">${state.entries.length?'高低仅表示所选心情的概略位置。':'还没有记录。你的轨迹会从这里开始。'}</span>`;}
function renderJournal(){const filter=$('#journal-filter').value;const entries=state.entries.filter(e=>filter==='all'||e.moods.includes(filter));$('#entry-count').textContent=`${entries.length} 个片刻`;$('#journal-list').innerHTML=entries.length?entries.map(e=>`<article class="card journal-entry"><time>${dateText(e.date)}</time><div class="entry-moods">${escapeHTML(moodNames(e))}</div><p>${escapeHTML(e.note||'只记录了心情，也很好。')}</p><div class="entry-bottom"><span>${escapeHTML(e.triggers.join(' / ')||'没有添加事件')} · 强度 ${e.intensity}/5</span><button data-delete="${escapeHTML(e.id)}" aria-label="删除 ${dateText(e.date)} 的日记">删除</button></div></article>`).join(''):empty('这里可以，慢慢写。',filter==='all'?'不需要完整的故事，一种感受就足够。':'暂时没有这种心情的记录。');}
function renderInsights(){const e=state.entries;if(!e.length){$('#insights-content').innerHTML=empty('先留下一颗星。','有了记录，就能在这里回看情绪与事件的联系。');return;}const counts=moods.map(m=>({...m,count:e.filter(x=>x.moods.includes(m.id)).length})).sort((a,b)=>b.count-a.count);const events=triggers.filter(t=>t!=='说不清').map(t=>({name:t,list:e.filter(x=>x.triggers.includes(t))})).filter(t=>t.list.length).sort((a,b)=>b.list.length-a.list.length);const days=new Set(e.map(x=>new Date(x.date).toDateString())).size;
 $('#insights-content').innerHTML=`<div class="insight-stats"><div class="card">记录的片刻<span class="stat-number">${e.length}</span></div><div class="card">有记录的日子<span class="stat-number">${days}</span></div><div class="card">常出现的心情<span class="stat-number">${counts[0].name}</span></div></div><div class="insight-grid"><section class="card"><h2>每一种感受，都被看见</h2><p>以下统计来自全部本地记录，多种心情可同时出现。</p>${counts.filter(m=>m.count).map(m=>`<div class="insight-row"><span>${m.name}</span><span>${m.count} 次</span></div>`).join('')}</section><section class="card"><span class="eyebrow">可能的线索</span><h2>是什么，牵动着心情？</h2>${events.length?events.slice(0,3).map(t=>{const freq=moods.map(m=>({name:m.name,count:t.list.filter(x=>x.moods.includes(m.id)).length})).sort((a,b)=>b.count-a.count)[0];return `<p>提到「${t.name}」的 ${t.list.length} 条记录中，${freq.count} 条同时出现「${freq.name}」。</p>`;}).join(''):'<p>下次记录时，可以选一个事件标签，看看生活与感受如何联系。</p>'}<p>${e.length<5?'记录还比较少，暂时不作规律判断。':'这些是共同出现的线索，不代表因果。回看原文，看看它是否符合你的感受。'}</p><a class="text-link" href="#journal">回到原始记录 ↗</a><hr><p class="small">本地统计 · 非 AI 诊断<br>趋势图以所选心情的概略位置取均值；“说不清”不参与高低计算，不代表心理健康评分。</p></section></div>`;
}
function renderCare(){const max=$('#duration-filter').value;$('#care-grid').innerHTML=practices.filter(p=>max==='all'||p.minutes<=Number(max)).map(p=>`<article class="card exercise-card"><span class="exercise-symbol" aria-hidden="true">${p.symbol}</span><span class="mini-label">${p.type} · ${p.minutes} 分钟</span><h2>${p.name}</h2><p>${p.description}</p><button class="outline" data-practice="${p.id}">开始练习 ↗</button></article>`).join('');const helpful=practices.map(p=>({...p,count:state.feedback.filter(f=>f.practice===p.id&&f.value==='better').length})).filter(p=>p.count).sort((a,b)=>b.count-a.count);$('#helpful-list').innerHTML=helpful.length?helpful.map(p=>`<div class="insight-row"><span>${p.name} · ${p.count} 次有帮助</span><button class="text-button" data-practice="${p.id}">再试一次 ↗</button></div>`).join(''):'<p>练习后告诉我们感受。你觉得有帮助的方式，会留在这里。</p>';}
let pendingDelete=null;function confirmDeletion(action){pendingDelete=action;$('#confirm-dialog').showModal();}$('#confirm-delete').addEventListener('click',()=>{pendingDelete?.();pendingDelete=null;$('#confirm-dialog').close();});
let interval=null,audio=null,activePractice=null,remaining=0,running=false,deadline=0,gain=null;
function stopPractice(){clearInterval(interval);interval=null;running=false;if(audio){audio.close().catch(()=>{});audio=null;}gain=null;}
function openPractice(id){stopPractice();activePractice=practices.find(p=>p.id===id);if(!activePractice)return;remaining=activePractice.minutes*60;const p=activePractice;$('#practice-content').innerHTML=`<div class="practice-center"><span class="eyebrow">${p.type} · 给自己一点时间</span><h2>${p.name}</h2><p>${p.description}</p><div class="practice-orb" id="orb">准备好了</div><div class="timer" id="timer">${formatTime(remaining)}</div><p id="step">${p.steps[0]}</p>${p.id==='music'?'<label for="volume">音量</label><input id="volume" type="range" min="0" max="100" value="20">':''}<div class="dialog-actions"><button class="primary" id="start-practice">开始</button><button class="outline" id="finish-practice">结束并反馈</button></div><p class="small">随时可以暂停。如果不舒服，就停下来。</p></div>`;$('#start-practice').addEventListener('click',togglePractice);$('#finish-practice').addEventListener('click',finishPractice);if($('#volume'))$('#volume').addEventListener('input',()=>{if(gain)gain.gain.value=Number($('#volume').value)/100*.12;});$('#practice-dialog').showModal();}
function formatTime(n){return `${Math.floor(n/60).toString().padStart(2,'0')}:${(n%60).toString().padStart(2,'0')}`;}
async function startAudio(){const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio){toast('当前浏览器不支持音景播放，可以尝试其他练习。');return false;}try{audio=new Audio();gain=audio.createGain();gain.gain.value=Number($('#volume').value)/100*.12;gain.connect(audio.destination);[174.61,261.63,349.23].forEach((f,i)=>{const o=audio.createOscillator();o.type='sine';o.frequency.value=f;const g=audio.createGain();g.gain.value=.3/(i+1);o.connect(g);g.connect(gain);o.start();});await audio.resume();return true;}catch{stopPractice();toast('音景暂时无法播放，请尝试其他练习。');return false;}}
async function togglePractice(){const button=$('#start-practice');if(running){remaining=Math.max(0,Math.ceil((deadline-Date.now())/1000));clearInterval(interval);running=false;if(audio)audio.suspend();button.textContent='继续';$('#orb').classList.remove('active');$('#orb').textContent='暂停一下';return;}button.disabled=true;if(activePractice.id==='music'){if(!audio){if(!await startAudio()){button.disabled=false;return;}}else await audio.resume();}button.disabled=false;running=true;deadline=Date.now()+remaining*1000;button.textContent='暂停';$('#orb').classList.add('active');$('#orb').textContent=activePractice.id==='breath'?'自然呼吸':'慢慢来';interval=setInterval(()=>{remaining=Math.max(0,Math.ceil((deadline-Date.now())/1000));$('#timer').textContent=formatTime(remaining);const elapsed=activePractice.minutes*60-remaining;const index=Math.min(activePractice.steps.length-1,Math.floor(elapsed/(activePractice.minutes*60/activePractice.steps.length)));$('#step').textContent=activePractice.steps[index];if(remaining===0)finishPractice();},250);}
function finishPractice(){stopPractice();$('#practice-content').innerHTML='<div class="practice-center"><span class="eyebrow">THANK YOU FOR TAKING THIS MOMENT</span><h2>现在，感觉如何？</h2><p>没有变化也没关系。找到适合自己的方式，需要一点时间。</p><div class="feedback-buttons"><button class="outline" data-feedback="better">轻松了一点</button><button class="outline" data-feedback="same">差不多</button><button class="outline" data-feedback="worse">更不舒服了</button><button class="text-button" data-feedback="skip">暂时不想回答</button></div></div>';$$('[data-feedback]').forEach(b=>b.addEventListener('click',()=>{const value=b.dataset.feedback;if(value!=='skip'&&!persist({...state,feedback:[...state.feedback,{practice:activePractice.id,value,date:new Date().toISOString()}]}))return;$('#practice-dialog').close();renderCare();if(value==='worse'){toast('先停下来休息一会儿，也可以找人陪陪你。');$('#support-dialog').showModal();}else toast(value==='better'?'已经记住这个对你有帮助的方式。':'谢谢你，给自己留了这一点时间。');}));}
setup();
if(document.modelContext?.registerTool){
 const lifecycle=new AbortController();
 try{Promise.resolve(document.modelContext.registerTool({name:'open_huanxing_view',title:'打开缓星功能板块',description:'仅切换缓星页面，不读取、保存或删除日记。',inputSchema:{type:'object',properties:{view:{type:'string',enum:['today','journal','insights','care','settings']}},required:['view'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||!['today','journal','insights','care','settings'].includes(input.view))throw new Error('Invalid view');location.hash=input.view;route();return {view:input.view};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}
 window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
}
